worker_processes 1;

events {
      worker_connections 1024;
}

http {
     upstream backend_servers {
          server 192.168.30.130:80;
          server 192.168.30.129:80;
     }

     server { 
          listen 80;
          server_name _;
 
          return 301 https://$host$request_uri;
     }
   
     server {
          listen 443 ssl;
          server_name _;

          ssl_certificate "C:/Users/cemin/OneDrive/바탕 화면/ngnix/nginx-1.29.7/certs/lb.crt";
          ssl_certificate_key "C:/Users/cemin/OneDrive/바탕 화면/ngnix/nginx-1.29.7/certs/lb.key";

          ssl_protocols TLSv1.2 TLSv1.3;


          location / {
                proxy_pass http://backend_servers;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forward-For $proxy_add_x_forwarded_for;
          }
     }
}